version: "3.4"

services:
  web:
    build:
      context: "."
      args:
        - "FLASK_ENV=${FLASK_ENV:-production}"
    env_file: ".docker.env"
    healthcheck:
      test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:5000/healthy}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    ports:
      - "${DOCKER_WEB_PORT:-127.0.0.1:5000}:5000"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    volumes:
      - '.:/app'
