version: "3.4"

services:
  web:
    build:
        context: "."
        args:
            - "FLASK_ENV=${FLASK_ENV:-production}"
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "snakeeyes.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/snakeeyes'
    ports:
      - '8000:8000'
